from .view_employee import *
from .view_contract import *
from .view_payroll import *
from .view_user import *
from .view_feducation import *
from .view_nfeducation import *
from .view_workexperience import *
from .view_languageskills import *
from .view_capacitybuilding import *
from .view_criminalrecord import *
from .view_sessionrefresher import *